// lib/CodeMirror/CodeMirror.vue
<script setup>
import { ref, onMounted } from 'vue'
import './style.css'
import CodeMirror from './cm.js'
const props = defineProps({
  text: { type: String, default: '' },
  autofocus: { type: Boolean, default: false },
  onChange: { type: Function, default: null },
  highlight: { type: Function, default: () => {} },
  onEnter: {
    type: Function,
    default: e => {
      return CodeMirror.Pass
    },
  },
})
const emit = defineEmits(['update:text'])
let editor
const el = ref(null)
const clear = function (doc) {
  doc.getAllMarks().forEach(m => m.clear())
}

onMounted(() => {
  // create codemirror instance
  editor = CodeMirror.fromTextArea(el.value, {
    autofocus: false,
    viewportMargin: Infinity,
    extraKeys: {
      Enter: props.onEnter,
    },
  })
  // update each keypress
  editor.on('change', doc => {
    if (props.onChange) {
      props.onChange()
    }
    clear(doc)
    let text = doc.getValue()
    emit('update:text', text)
    let offsets = props.highlight(text) || []
    offsets.forEach(m => {
      let start = doc.posFromIndex(m.start)
      let end = doc.posFromIndex(m.end)
      editor.markText(start, end, {
        className: m.tag,
      })
    })
  })
  CodeMirror.signal(editor, 'change', editor)
  if (props.autofocus === true) {
    setTimeout(() => {
      editor.focus()
      editor.setCursor(editor.lineCount(), 0)
    }, 500)
  }
})
</script>

<template>
  <div class="outside">
    <textarea ref="el" class="textarea" tabindex="0" :value="text" />
  </div>
</template>

<style>
.outside {
  margin: 2rem;
}
.CodeMirror {
  height: auto;
  border-left: 4px solid lightsteelblue !important;
  border-bottom: none !important;
  text-align: left !important;
}
.tag {
  color: #2d85a8;
  border-radius: 5px;
  opacity: 1;
}
</style>

// dates/CodeMirror/CodeMirror.svelte
<script>
  import { onMount } from 'svelte'
  import CodeMirror from './lib.js'
  export let text = ''
  export let autofocus = true
  let editor
  let el
  export let highlight = () => {}
  export let onEnter = e => {
    return CodeMirror.Pass
  }
  const clear = function(doc) {
    doc.getAllMarks().forEach(m => m.clear())
  }

  onMount(() => {
    // create codemirror instance
    editor = CodeMirror.fromTextArea(el, {
      autofocus: autofocus,
      extraKeys: {
        Enter: onEnter
      }
    })
    // update each keypress
    editor.on('change', doc => {
      clear(doc)
      text = doc.getValue()
      let offsets = highlight(text)
      offsets.forEach(m => {
        let start = doc.posFromIndex(m.start)
        let end = doc.posFromIndex(m.end)
        editor.markText(start, end, {
          className: m.tag
        })
      })
    })
    CodeMirror.signal(editor, 'change', editor)

    setTimeout(() => {
      editor.focus()
      editor.setCursor(editor.lineCount(), 0)
    }, 500)
  })
</script>

<style>
  :global(.CodeMirror) {
    /* height: 5rem !important; */
    width: 50rem !important;
    /* background-color: #1a1c1c !important; */
    /* color: #d9d9d9 !important; */
    border-left: 4px solid lightsteelblue !important;
    border-bottom: none !important;
    text-align: left !important;
    font-size: 1.7rem;
  }
  :global(.tag) {
    color: #2d85a8;
    /* background-color: #2d85a8; */
    /* color: #d9d9d9 !important; */
    /* margin: 5px; */
    /* padding: 5px; */
    border-radius: 5px;
    opacity: 1;
  }
</style>

<textarea class="textarea" bind:this={el} tabindex="0 ">{text}</textarea>
